/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PInput: typeof import('pxd/components/input')['default']
    PProgress: typeof import('pxd/components/progress')['default']
    PSlider: typeof import('pxd/components/slider')['default']
  }
}
