/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('pxd/components/button')['default']
    PColorScheme: typeof import('pxd/components/color-scheme')['default']
    PConfigProvider: typeof import('pxd/components/config-provider')['default']
    PHoldButton: typeof import('pxd/components/hold-button')['default']
    PInput: typeof import('pxd/components/input')['default']
    PLinkButton: typeof import('pxd/components/link-button')['default']
    PMoreButton: typeof import('pxd/components/more-button')['default']
  }
}
